### ISSUE TITLE
Sums with precision 2

### ISSUE THREAD

**Issue by josesanch** [funcool/decimal#6]
I'm not sure why using precision 2 adding numbers to numbers greater than 100 seens wrong.

```

(let [mydec (dc/config {:precision 2 :rounding :round-down})]
          (str (dc/+ (mydec "100") (mydec "1")))) => 100

(let [mydec (dc/config {:precision 2 :rounding :round-up})]
         (str (dc/+ (mydec "100") (mydec "1")))) => 110
 
(let [mydec (dc/config {:precision 5 :rounding :round-down})]
      (str (dc/+ (mydec "100") (mydec "1")))) => 101

(let [mydec (dc/config {:precision 5 :rounding :round-up})]
          (str (dc/+ (mydec "100") (mydec "1")))) => 101

```

**Comment by niwinz** [comment]
Because precision is not about decimals is about most significant numbers, in case of setting up precision 2, you are telling that only first `10` of `100` is significant, so when you sum `1` to `100` you have `101` that taking most significant numbers is rounded up to `110`.

Try to use precision 3 and the result will be the expcted.

**Comment by josesanch** [comment]
I've seen that the library is based in decimal.js and that is the way it's works.

Thank you
